name: ec2-creation
on:
  push:
    paths:
      - '.github/workflows/create.yaml'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v5
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run: terraform init
